name: Build and Deploy TiddlyWiki to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "tiddlers/**"

permissions:
  # For GitHub Pages ephemeral deployments
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # environment: github-pages is set at the job level (not under "with:")
    environment: github-pages

    steps:
      # 1. Check out code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # 3. Install TiddlyWiki globally
      - name: Install TiddlyWiki
        run: npm install -g tiddlywiki

      # 4. Build the TiddlyWiki site
      - name: Build TiddlyWiki
        run: tiddlywiki . --build index  # Outputs to ./output by default

      # 5. Debug: Check what's actually in ./output
      - name: Debug Output Directory
        run: |
          echo "Contents of ./output:"
          ls -R ./output || echo "No files in ./output"

      # 6. Upload the ephemeral GitHub Pages artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Must match where your index.html and others are generated
          path: ./output

      # 7. Deploy
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        # The warning about 'environment' means you should NOT put environment in 'with:'
        # Instead, the environment is declared at the job level above.

