name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install TiddlyWiki CLI
        run: npm install -g tiddlywiki

      - name: Build TiddlyWiki
        run: tiddlywiki . --build index

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./output  # adjust if your build outputs elsewhere

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
