name: Build TiddlyWiki

on:
  push:
    branches:
      - main
    paths:
      - "tiddlers/**"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install TiddlyWiki
        run: npm install -g tiddlywiki

      - name: Build TiddlyWiki
        run: tiddlywiki . --build index  # Outputs files into the output directory

      - name: Debug Output Directory
        run: |
          echo "Contents of ./output:"
          ls -R ./output || echo "No files in ./output"

      - name: Upload TiddlyWiki Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./output
          name: tiddlywiki-artifact
