nname: Auto-Update TiddlyWiki

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install TiddlyWiki CLI
      - run: npm install -g tiddlywiki

      # Step 4: Build the index.html file
      - run: tiddlywiki . --build index

      # Step 5: Deploy the updated wiki to GitHub Pages
      - name: Deploy Updated Wiki
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: output

