name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install TiddlyWiki
        run: npm install -g tiddlywiki

      - name: Build TiddlyWiki
        run: tiddlywiki . --build index

      - name: Debug Output
        # This step lists the contents of the output directory for debugging
        run: ls -R ./output || echo "No files in output"

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './output'  # Correct path since files are directly in output
          name: github-pages  # Explicitly name the artifact to avoid confusion

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
