name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install TiddlyWiki
        run: npm install -g tiddlywiki

      - name: Build TiddlyWiki
        # Must place output in the folder you reference in "Upload Pages Artifact"
        run: tiddlywiki . --build index

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # IMPORTANT: Make sure this folder actually has the final HTML files
          path: ./output  # or './output/**/*' if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
