name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install TiddlyWiki
        run: npm install -g tiddlywiki

      - name: Build TiddlyWiki
        run: tiddlywiki . --build index  # Outputs files directly into the root directory

      - name: Debug Build Directory
        run: |
          echo "Contents of the root directory:"
          ls -R . || echo "No files in root directory"

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'  # Upload all files in the main directory
          name: github-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
